In [1]:
import pandas as pd
import numpy as np

In [63]:
dfi1 = pd.read_csv('/home/poyraden/Analysis/JOSIEfiles/Paper/2017/184_7.csv')
dfi1

ParserError: Error tokenizing data. C error: Expected 4 fields in line 4, saw 24

In [56]:
dfa = pd.read_csv('/home/poyraden/Analysis/JOSIEfiles/Proccessed/Josie2017_Data_Public.csv')

In [57]:
dfa[(dfa.Sim == 182) & (dfa.Team==6)]

AttributeError: 'DataFrame' object has no attribute 'Sim'

In [65]:
df = pd.read_csv(f'/home/poyraden/Analysis/JOSIEfiles/Proccessed/Josie2017_calibrated_sm_hv.csv')

/home/poyraden/.local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3553: DtypeWarning: Columns (58,78,85) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [73]:
df[['Date','Header_PFcor','PFcor','SerialNr']]

              Date  Header_PFcor    PFcor SerialNr
0       10/27/2017         3.367  3.36662  2Z21232
1       10/27/2017         3.367  3.36662  2Z21232
2       10/27/2017         3.367  3.36662  2Z21232
3       10/27/2017         3.367  3.36662  2Z21232
4       10/27/2017         3.367  3.36662  2Z21232
...            ...           ...      ...      ...
237066  10/20/2017         3.725  3.72498  6A33213
237067  10/20/2017         3.725  3.72498  6A33213
237068  10/20/2017         3.725  3.72498  6A33213
237069  10/20/2017         3.725  3.72498  6A33213
237070  10/20/2017         3.725  3.72498  6A33213

[237071 rows x 4 columns]

In [75]:
df['Date']
df['Date2'] = pd.to_datetime(df['Date'])

In [76]:
df[['Date','Date2']]

              Date      Date2
0       10/27/2017 2017-10-27
1       10/27/2017 2017-10-27
2       10/27/2017 2017-10-27
3       10/27/2017 2017-10-27
4       10/27/2017 2017-10-27
...            ...        ...
237066  10/20/2017 2017-10-20
237067  10/20/2017 2017-10-20
237068  10/20/2017 2017-10-20
237069  10/20/2017 2017-10-20
237070  10/20/2017 2017-10-20

[237071 rows x 2 columns]

In [66]:
print(list(df))

['Unnamed: 0', 'Unnamed: 0.1', 'Sim', 'Team', 'iB0', 'iB1', 'iB2', 'ENSCI', 'Sol', 'ADX', 'Buf', 'PO3', 'PO3_OPM', 'Tsim', 'Pair', 'IM', 'I_OPM_kom', 'I_OPM_jma', 'PFcor', 'TPext', 'Tpump_cor', 'unc_Tpump_cor', 'unc_Tpump', 'Tpump_cor.1', 'unc_Tpump_cor.1', 'deltat', 'unc_deltat', 'deltat_ppi', 'unc_deltat_ppi', 'Cpf_kom', 'unc_Cpf_kom', 'Cpf', 'unc_Cpf', 'Cpf_jma', 'unc_Cpf_jma', 'PFcor_kom', 'PFcor_jma', 'PO3_calc', 'PO3_dqa', 'I_slow_conv_ib1_decay', 'Ifast_minib0_deconv', 'Ifast_minib0_deconv_ib1_decay', 'Ifast_minib0', 'Ifast_minib0_ib1_decay', 'Islow_conv', 'Ifast_deconv_ib1_decay', 'Ifast_minib0_deconv_sm10', 'Year', 'Unnamed: 0.1.1', 'index', 'Tact', 'Tair', 'Tinlet', 'TPint', 'I_Pump', 'VMRO3', 'VMRO3_OPM', 'ADif_PO3S', 'RDif_PO3S', 'Z', 'Header_Team', 'Header_Sim', 'Header_PFunc', 'Header_PFcor', 'Header_IB1', 'Simulator_RunNr', 'Date', 'Ini_Prep_Date', 'Prep_SOP', 'SerialNr', 'SerNr', 'Date_1', 'SondeAge', 'Solutions', 'Volume_Cathode', 'ByPass_Cell', 'Current_10min_after_noO3', 'Resp_Time_4_1p5_sec', 'RespTime_1minOver2min', 'Final_BG', 'T100', 'mlOvermin', 'T100_post', 'mlOverminp1', 'RespTime_4_1p5_sec_p1', 'RespTime_1minOver2min_microamps', 'PostTestSolution_Lost_gr', 'PumpMotorCurrent', 'PumpMotorCurrent_Post', 'PF_Unc', 'PF_Cor', 'BG', 'plog', 'Tcell', 'TcellC', 'Pw', 'massloss', 'Tboil', 'total_massloss', 'I_conv_slow', 'I_conv_slow_komhyr', 'IMminusIB0', 'tmp', 'IM_gsm', 'IMminusIB0_gsm', 'Islow', 'Ifast', 'Ifast_deconv', 'ADif', 'RDif', 'ADif_cor', 'RDif_cor', 'PO3_cor', 'ADif_pre', 'RDif_pre', 'ADif_pre_cor', 'RDif_pre_cor', 'IminusiB1', 'R', 'I_corrected', 'ADif_cal', 'RDif_cal']

In [46]:
dfmeta = pd.read_excel("/home/poyraden/Analysis/JOSIEfiles/JOSIE_Table_2017_summary_upd.xlsx")
print(list(dfmeta))

['Sim', 'Simulator Run #', 'Date', 'Team', 'Initial Prep Date', 'Prep SOP', 'serial #', 'ENSCI', 'sernr', 'Date.1', 'sondeage', 'Solutions', 'Sol', 'Buf', 'Volume Cathode', 'ByPass Cell', 'current 10 min after no ozone', ' Resp Time 4-1.5 (sec)', 'Resp Time  1min/2min (mircroamps)?', 'Final BG', 'iB0', 'iB1', 'iB2', 'T100', 'ml/min', 'T100 post', 'ml/min.1', ' Resp Time 4-1.5 (sec).1', 'Resp Time  1min/2min (microamps)', 'post test solution lost (grams)', 'pump motor current', 'pump motor current (post)', 'PF_Unc', 'PF_Cor', 'BG']

In [68]:
dfmeta[['Date','Sim','Team','Prep SOP', 'serial #', 'Solutions', 'ml/min','Sol', 'Buf', 'Volume Cathode','iB0', 'iB1', 'iB2', 'post test solution lost (grams)','T100', 'ml/min', 'T100 post', ]]

,Date,Sim,Team,Prep SOP,serial #,Solutions,ml/min,Sol,Buf,Volume Cathode,iB0,iB1,iB2,post test solution lost (grams),T100,ml/min,T100 post
0,10/11/2017,171,1,Vaisala,6A33216,1.0%-1.0B,237.72,1.0,1.0,2.5,0.02,0.15,0.02,0.823,25.240,237.72,-99.99
1,10/11/2017,171,2,Wallops,6A33298,1.0%-1.0B +Alconox,224.38,1.0,1.0,3.0,0.14,0.08,0.02,0.938,26.740,224.38,-99.99
2,10/11/2017,171,3,SHADOZ,Z29456,0.5%-0.5B,202.43,0.5,0.5,3.0,0.02,0.08,0.04,0.515,29.640,202.43,29.55
3,10/11/2017,171,4,NOAA -No_bypass,Z29452,1.0%-0.1B,198.48,1.0,0.1,3.0,0.00,0.08,0.02,0.476,30.230,198.48,30.37
4,10/12/2017,172,1,Vaisala,6A33211,1.0%-1.0B,221.53,1.0,1.0,2.5,0.01,0.16,0.04,0.725,27.084,221.53,27.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,11/2/2017,190,8,WMO-SOP 1.0 SHADOZ expansion,2Z31525,1.0%-0.1B,200.07,1.0,0.1,3.0,0.01,0.01,0.02,0.415,29.990,200.07,29.87
80,11/2/2017,191,5,Vaisala,6A32265,1.0%-1.0B,208.55,1.0,1.0,3.0,0.00,0.20,0.09,0.621,28.770,208.55,29.18
81,11/2/2017,191,6,Changfeng (?ENSCI),2Z31506,0.5%-0.5B,204.36,0.5,0.5,3.0,0.02,0.06,0.04,0.481,29.360,204.36,29.29
82,11/2/2017,191,7,La Reunion,2Z31510,0.5%-0.5B,205.13,0.5,0.5,2.5,0.02,0.06,0.03,0.533,29.250,205.13,29.19
83,11/2/2017,191,8,Fujiwara (?ENSCI),2Z31503,0.5%-0.5B,195.44,0.5,0.5,3.0,0.01,0.05,0.04,0.523,30.700,195.44,28.95

In [36]:
df0 = pd.read_csv("/home/poyraden/Analysis/JOSIEfiles/Proccessed/Josie2017_Data_2023paper_ib2.csv")

/home/poyraden/.local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3553: DtypeWarning: Columns (16,41,51) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [38]:
print(list(df0))

['Unnamed: 0', 'Tact', 'Tsim', 'Pair', 'Tair', 'Tinlet', 'IM', 'TPint', 'TPext', 'PFcor', 'I_Pump', 'PO3', 'VMRO3', 'PO3_OPM', 'VMRO3_OPM', 'ADif_PO3S', 'RDif_PO3S', 'Z', 'Header_Team', 'Header_Sim', 'Header_PFunc', 'Header_PFcor', 'Header_IB1', 'Sim', 'Simulator_RunNr', 'Date', 'Team', 'Ini_Prep_Date', 'Prep_SOP', 'SerialNr', 'ENSCI', 'SerNr', 'Date_1', 'SondeAge', 'Solutions', 'Sol', 'Buf', 'Volume_Cathode', 'ByPass_Cell', 'Current_10min_after_noO3', 'Resp_Time_4_1p5_sec', 'RespTime_1minOver2min', 'Final_BG', 'iB0', 'iB1', 'iB2', 'T100', 'mlOvermin', 'T100_post', 'mlOverminp1', 'RespTime_4_1p5_sec_p1', 'RespTime_1minOver2min_microamps', 'PostTestSolution_Lost_gr', 'PumpMotorCurrent', 'PumpMotorCurrent_Post', 'PF_Unc', 'PF_Cor', 'BG', 'unc_Tpump', 'Tpump_cor', 'unc_Tpump_cor', 'deltat', 'unc_deltat', 'deltat_ppi', 'unc_deltat_ppi', 'Cpf_kom', 'unc_Cpf_kom', 'Cpf', 'unc_Cpf', 'plog', 'Cpf_jma', 'unc_Cpf_jma', 'PFcor_kom', 'PFcor_jma', 'I_OPM_jma', 'I_OPM_kom', 'PO3_calc', 'PO3_dqa', 'Tcell', 'TcellC', 'Pw', 'massloss', 'Tboil', 'total_massloss', 'I_conv_slow', 'I_conv_slow_komhyr']

In [52]:
df0[[ 'SerialNr', 'ENSCI', 'SerNr', 'Date', 'Team', 'Ini_Prep_Date','Header_PFunc', 'Header_PFcor','PFcor', 'iB0', 'iB1', 'iB2']]

,SerialNr,ENSCI,SerNr,Date,Team,Ini_Prep_Date,Header_PFunc,Header_PFcor,PFcor,iB0,iB1,iB2
0,6A33301,0,33301,10/20/2017,2,10/14/2017,3.533,3.485,3.48498,0.00,0.01,0.02
1,6A33301,0,33301,10/20/2017,2,10/14/2017,3.533,3.485,3.48498,0.00,0.01,0.02
2,6A33301,0,33301,10/20/2017,2,10/14/2017,3.533,3.485,3.48498,0.00,0.01,0.02
3,6A33301,0,33301,10/20/2017,2,10/14/2017,3.533,3.485,3.48498,0.00,0.01,0.02
4,6A33301,0,33301,10/20/2017,2,10/14/2017,3.533,3.485,3.48498,0.00,0.01,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...
296267,2Z32856,1,32856,10/30/2017,6,10/28/2017,3.532,3.484,3.48399,0.01,0.02,0.04
296268,2Z32856,1,32856,10/30/2017,6,10/28/2017,3.532,3.484,3.48399,0.01,0.02,0.04
296269,2Z32856,1,32856,10/30/2017,6,10/28/2017,3.532,3.484,3.48399,0.01,0.02,0.04
296270,2Z32856,1,32856,10/30/2017,6,10/28/2017,3.532,3.484,3.48399,0.01,0.02,0.04
296271,2Z32856,1,32856,10/30/2017,6,10/28/2017,3.532,3.484,3.48399,0.01,0.02,0.04

In [25]:
df = pd.read_csv(f'/home/poyraden/Analysis/JOSIEfiles/Proccessed/Josie2017_calibrated_sm_hv.csv')

/home/poyraden/.local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3553: DtypeWarning: Columns (58,78,85) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [27]:
df

,Unnamed: 0,Unnamed: 0.1,Sim,Team,iB0,iB1,iB2,ENSCI,Sol,ADX,...,PO3_cor,ADif_pre,RDif_pre,ADif_pre_cor,RDif_pre_cor,IminusiB1,R,I_corrected,ADif_cal,RDif_cal
0,0,11565,184,7,0.03,0.07,0.09,1,0.5,NaN,...,0.000000,-0.231293,-5.378586,-4.300250,-100.000000,1.05041,1.720001,0.000000,-1.110119,-100.000000
1,1,11566,184,7,0.03,0.07,0.09,1,0.5,NaN,...,4.359031,-0.224225,-5.214221,0.058780,1.366909,1.05204,1.720001,1.106061,-0.003853,-0.347122
2,2,11567,184,7,0.03,0.07,0.09,1,0.5,NaN,...,4.359116,-0.197468,-4.592010,0.058866,1.368896,1.05896,1.720001,1.106097,-0.003831,-0.345168
3,3,11568,184,7,0.03,0.07,0.09,1,0.5,NaN,...,4.351881,-0.184868,-4.311702,0.064284,1.499309,1.05896,1.720001,1.104276,-0.002401,-0.216961
4,4,11569,184,7,0.03,0.07,0.09,1,0.5,NaN,...,4.335709,-0.127275,-3.010030,0.107332,2.538377,1.05855,1.723939,1.100112,0.008738,0.800635
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237066,237066,285763,181,1,0.00,0.01,0.03,0,1.0,NaN,...,8.235209,0.545733,6.809427,0.220830,2.755419,2.14582,-2.168603,2.110135,0.101117,5.033172
237067,237067,285764,181,1,0.00,0.01,0.03,0,1.0,NaN,...,8.179099,0.520116,6.489788,0.164720,2.055308,2.13931,-2.168502,2.095669,0.086734,4.317434
237068,237068,285765,181,1,0.00,0.01,0.03,0,1.0,NaN,...,8.143499,0.507462,6.331891,0.129120,1.611109,2.13605,-2.168402,2.086459,0.077608,3.863282
237069,237069,285766,181,1,0.00,0.01,0.03,0,1.0,NaN,...,8.137473,0.409168,5.105430,0.123094,1.535912,2.11163,-2.168653,2.085136,0.076077,3.786685
237070,237070,285767,181,1,0.00,0.01,0.03,0,1.0,NaN,...,8.155464,0.461147,5.753992,0.141085,1.760397,2.12466,-2.168653,2.089746,0.080687,4.016147

In [28]:
dff=pd.read_csv('/home/poyraden/Analysis/JOSIEfiles/Proccessed/Josie2017_Data_Public.csv')

In [30]:
print(list(dff))

['Unnamed: 0', 'Sim_Time', 'Data_Index', 'Pair_Pressure_ESC', 'Tair_Pressure_ESC', 'IM_Cell_Measured', 'IS_Cell_Slow', 'IF_Cell_Fast', 'IFDS_Cell_Fast_Deconv_Smooth', 'Pump_T_Ext', 'Pump_T_Int', 'Absorption_Eff', 'Pump_Eff_Conv', 'Conversion_Eff_Conv', 'Pump_Eff_TRCC', 'Conversion_Eff_TRCC', 'PO3_Conv', 'PO3_TRC', 'PO3_TRCC', 'PO3_OPM', 'Unc_PO3_Conv', 'Unc_PO3_TRC', 'Unc_PO3_TRCC', 'Unc_PO3_OPM']

In [34]:
dff = dff.drop(['Unnamed: 0'], axis=1)

In [35]:
dff

,Sim_Time,Data_Index,Pair_Pressure_ESC,Tair_Pressure_ESC,IM_Cell_Measured,IS_Cell_Slow,IF_Cell_Fast,IFDS_Cell_Fast_Deconv_Smooth,Pump_T_Ext,Pump_T_Int,...,Pump_Eff_TRCC,Conversion_Eff_TRCC,PO3_Conv,PO3_TRC,PO3_TRCC,PO3_OPM,Unc_PO3_Conv,Unc_PO3_TRC,Unc_PO3_TRCC,Unc_PO3_OPM
0,0.0,0.0,999.99900,299.151,1.14041,1.140410,1.114816,0.000000,300.920,301.186,...,3.366620,1.017200,4.068958,0.000000,0.000000,4.300250,0.038863,NaN,0.031659,0.02
1,2.0,2.0,999.99900,299.183,1.14204,1.140369,1.115605,1.125085,300.955,301.242,...,3.366620,1.017200,4.076026,4.359031,4.285323,4.300250,0.038849,NaN,0.031642,0.02
2,4.0,4.0,999.99900,299.170,1.14896,1.140329,1.116337,1.125122,300.953,301.238,...,3.366620,1.017200,4.102782,4.359116,4.285407,4.300250,0.038788,NaN,0.031572,0.02
3,6.0,6.0,999.99900,299.157,1.14896,1.140284,1.116870,1.123269,300.950,301.234,...,3.366620,1.017200,4.102728,4.351881,4.278294,4.287597,0.038788,NaN,0.031572,0.02
4,8.0,8.0,996.58300,298.923,1.14855,1.140219,1.117040,1.119077,300.948,301.230,...,3.366534,1.017239,4.101102,4.335709,4.262231,4.228377,0.038791,NaN,0.031576,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237066,6992.0,6992.0,7.73468,214.838,2.17582,3.553813,2.086095,2.064374,284.859,292.387,...,3.192342,0.978314,8.560112,8.235209,8.417757,8.014379,0.036693,NaN,0.035309,0.02
237067,6994.0,6994.0,7.73188,214.766,2.16931,3.551754,2.082836,2.050224,284.859,292.387,...,3.192212,0.978315,8.534495,8.179099,8.360395,8.014379,0.036701,NaN,0.035320,0.02
237068,6996.0,6996.0,7.72909,214.693,2.16605,3.549699,2.079055,2.041216,284.859,292.387,...,3.192082,0.978316,8.521841,8.143499,8.323997,8.014379,0.036705,NaN,0.035327,0.02
237069,6998.0,6998.0,7.73608,214.874,2.14163,3.547646,2.075500,2.039916,284.859,292.387,...,3.192408,0.978313,8.423548,8.137473,8.317858,8.014379,0.036732,NaN,0.035350,0.02
237070,7000.0,7000.0,7.73608,214.874,2.15466,3.545596,2.072677,2.044426,284.859,292.387,...,3.192408,0.978313,8.475526,8.155464,8.336248,8.014379,0.036717,NaN,0.035334,0.02

In [2]:
pre = '_sm_hv'

In [18]:
df17c = pd.read_csv(f"/home/poyraden/Analysis/JOSIEfiles/Proccessed/Josie2017_deconv_2023paper_ib2{pre}.csv", low_memory=False)

In [19]:
print(list(df17c))

['Unnamed: 0', 'index', 'Unnamed: 0.1', 'Tact', 'Tsim', 'Pair', 'Tair', 'Tinlet', 'IM', 'TPint', 'TPext', 'PFcor', 'I_Pump', 'PO3', 'VMRO3', 'PO3_OPM', 'VMRO3_OPM', 'ADif_PO3S', 'RDif_PO3S', 'Z', 'Header_Team', 'Header_Sim', 'Header_PFunc', 'Header_PFcor', 'Header_IB1', 'Sim', 'Simulator_RunNr', 'Date', 'Team', 'Ini_Prep_Date', 'Prep_SOP', 'SerialNr', 'ENSCI', 'SerNr', 'Date_1', 'SondeAge', 'Solutions', 'Sol', 'Buf', 'Volume_Cathode', 'ByPass_Cell', 'Current_10min_after_noO3', 'Resp_Time_4_1p5_sec', 'RespTime_1minOver2min', 'Final_BG', 'iB0', 'iB1', 'iB2', 'T100', 'mlOvermin', 'T100_post', 'mlOverminp1', 'RespTime_4_1p5_sec_p1', 'RespTime_1minOver2min_microamps', 'PostTestSolution_Lost_gr', 'PumpMotorCurrent', 'PumpMotorCurrent_Post', 'PF_Unc', 'PF_Cor', 'BG', 'unc_Tpump', 'Tpump_cor', 'unc_Tpump_cor', 'deltat', 'unc_deltat', 'deltat_ppi', 'unc_deltat_ppi', 'Cpf_kom', 'unc_Cpf_kom', 'Cpf', 'unc_Cpf', 'plog', 'Cpf_jma', 'unc_Cpf_jma', 'PFcor_kom', 'PFcor_jma', 'I_OPM_jma', 'I_OPM_kom', 'PO3_calc', 'PO3_dqa', 'Tcell', 'TcellC', 'Pw', 'massloss', 'Tboil', 'total_massloss', 'I_conv_slow', 'I_conv_slow_komhyr', 'IMminusIB0', 'tmp', 'IM_gsm', 'IMminusIB0_gsm', 'Islow', 'Islow_conv', 'Ifast', 'Ifast_minib0', 'Ifast_deconv', 'Ifast_minib0_deconv', 'Ifast_minib0_deconv_sm10']

In [20]:
dftc = df17c[(df17c.Sim == 178) & (df17c.Team ==1)]

In [3]:
df = pd.read_csv(f'/home/poyraden/Analysis/JOSIEfiles/Proccessed/Josie2017_calibrated{pre}.csv')

/home/poyraden/.local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3553: DtypeWarning: Columns (58,78,85) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [5]:
print(list(df))

['Unnamed: 0', 'Unnamed: 0.1', 'Sim', 'Team', 'iB0', 'iB1', 'iB2', 'ENSCI', 'Sol', 'ADX', 'Buf', 'PO3', 'PO3_OPM', 'Tsim', 'Pair', 'IM', 'I_OPM_kom', 'I_OPM_jma', 'PFcor', 'TPext', 'Tpump_cor', 'unc_Tpump_cor', 'unc_Tpump', 'Tpump_cor.1', 'unc_Tpump_cor.1', 'deltat', 'unc_deltat', 'deltat_ppi', 'unc_deltat_ppi', 'Cpf_kom', 'unc_Cpf_kom', 'Cpf', 'unc_Cpf', 'Cpf_jma', 'unc_Cpf_jma', 'PFcor_kom', 'PFcor_jma', 'PO3_calc', 'PO3_dqa', 'I_slow_conv_ib1_decay', 'Ifast_minib0_deconv', 'Ifast_minib0_deconv_ib1_decay', 'Ifast_minib0', 'Ifast_minib0_ib1_decay', 'Islow_conv', 'Ifast_deconv_ib1_decay', 'Ifast_minib0_deconv_sm10', 'Year', 'Unnamed: 0.1.1', 'index', 'Tact', 'Tair', 'Tinlet', 'TPint', 'I_Pump', 'VMRO3', 'VMRO3_OPM', 'ADif_PO3S', 'RDif_PO3S', 'Z', 'Header_Team', 'Header_Sim', 'Header_PFunc', 'Header_PFcor', 'Header_IB1', 'Simulator_RunNr', 'Date', 'Ini_Prep_Date', 'Prep_SOP', 'SerialNr', 'SerNr', 'Date_1', 'SondeAge', 'Solutions', 'Volume_Cathode', 'ByPass_Cell', 'Current_10min_after_noO3', 'Resp_Time_4_1p5_sec', 'RespTime_1minOver2min', 'Final_BG', 'T100', 'mlOvermin', 'T100_post', 'mlOverminp1', 'RespTime_4_1p5_sec_p1', 'RespTime_1minOver2min_microamps', 'PostTestSolution_Lost_gr', 'PumpMotorCurrent', 'PumpMotorCurrent_Post', 'PF_Unc', 'PF_Cor', 'BG', 'plog', 'Tcell', 'TcellC', 'Pw', 'massloss', 'Tboil', 'total_massloss', 'I_conv_slow', 'I_conv_slow_komhyr', 'IMminusIB0', 'tmp', 'IM_gsm', 'IMminusIB0_gsm', 'Islow', 'Ifast', 'Ifast_deconv', 'ADif', 'RDif', 'ADif_cor', 'RDif_cor', 'PO3_cor', 'ADif_pre', 'RDif_pre', 'ADif_pre_cor', 'RDif_pre_cor', 'IminusiB1', 'R', 'I_corrected', 'ADif_cal', 'RDif_cal']

In [11]:
# print(df.drop_duplicates(['Sim','Team'])[['Sim','Team']])

In [8]:
dft = df[(df.Sim == 178) & (df.Team ==1)]

In [17]:
dft[['Tsim', 'Pair','Tair','IM','I_conv_slow','Ifast_minib0_deconv_sm10']]

,Tsim,Pair,Tair,IM,I_conv_slow,Ifast_minib0_deconv_sm10
219994,0.0,999.99900,296.951,1.12820,1.128200,0.000000
219995,2.0,999.12700,296.994,1.12413,1.128167,1.091282
219996,4.0,999.47600,296.977,1.11599,1.128135,1.090789
219997,6.0,999.82500,296.960,1.11966,1.128131,1.090824
219998,8.0,994.65700,297.051,1.12169,1.128137,1.090491
...,...,...,...,...,...,...
223490,6992.0,7.89849,213.727,1.98535,3.467395,1.780513
223491,6994.0,7.90268,213.723,1.97192,3.465419,1.806871
223492,6996.0,7.89010,213.736,1.96174,3.463446,1.828428
223493,6998.0,7.89010,213.736,1.97069,3.461475,1.839231
223494,7000.0,7.89010,213.736,1.95360,3.459507,1.844040

In [24]:
dftc[['Tsim', 'Pair','Tair','IM','I_conv_slow','Ifast_minib0','Ifast_minib0_deconv_sm10','TPext','TPint']]

,Tsim,Pair,Tair,IM,I_conv_slow,Ifast_minib0,Ifast_minib0_deconv_sm10,TPext,TPint
189225,0.0,999.99900,296.951,1.12820,1.128200,1.103008,0.000000,300.165,299.62
189226,2.0,999.12700,296.994,1.12413,1.128167,1.101943,1.091282,300.218,299.62
189227,4.0,999.47600,296.977,1.11599,1.128135,1.100930,1.090789,300.214,299.62
189228,6.0,999.82500,296.960,1.11966,1.128131,1.100012,1.090824,300.210,299.62
189229,8.0,994.65700,297.051,1.12169,1.128137,1.099147,1.090491,300.206,299.62
...,...,...,...,...,...,...,...,...,...
192721,6992.0,7.89849,213.727,1.98535,3.467395,1.882783,1.780513,286.898,278.75
192722,6994.0,7.90268,213.723,1.97192,3.465419,1.875887,1.806871,286.898,278.75
192723,6996.0,7.89010,213.736,1.96174,3.463446,1.871576,1.828428,286.898,278.75
192724,6998.0,7.89010,213.736,1.97069,3.461475,1.868637,1.839231,286.898,278.75
192725,7000.0,7.89010,213.736,1.95360,3.459507,1.866403,1.844040,286.898,278.75